# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deployment
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/projects/24001154-12-kp1-bingleshopecommerce-platinum
          git pull origin main
          git status
          npm install
          pm2 restart app
